api:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: "/api/v{version}"
    defaults: {version: 1.1}
    requirements:
        version: '^[1-9]+\.[0-9]+'

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"