# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_MANAGER:     ROLE_USER
        ROLE_ADMIN:       ROLE_MANAGER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        user_provider:
            entity:
                class: AppBundle:User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

    access_control:
        #- { path: ^/api/doc, methods: [GET], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/api/v(.*)/users/code, methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/api/v(.*)/users, methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/api/v(.*)/*, roles: ROLE_USER }
        #- { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }