services:

    # Listeners Doctrine
    app.listener.doctrine.user:
        class: AppBundle\EventListener\Doctrine\UserListener
        calls:
            - [setEncoderFactory, ['@security.encoder_factory']]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    #Normalizers
    app.normalizer.exception:
        class: AppBundle\Serializer\Normalizer\ExceptionNormalizer
        arguments: ["%kernel.environment%"]
        tags:
            - { name: serializer.normalizer }

    #Repositories
    app.repository.user:
        class: AppBundle\Repository\DefaultRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\User

    app.repository.locality:
        class: AppBundle\Repository\DefaultRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Locality

    app.repository.cinema:
        class: AppBundle\Repository\DefaultRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Cinema

    app.repository.cinema_seat:
        class: AppBundle\Repository\DefaultRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\CinemaSeat

    app.repository.cinema_manager:
        class: AppBundle\Repository\DefaultRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\CinemaManager

    app.repository.genre:
        class: AppBundle\Repository\DefaultRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Genre

    app.repository.seance:
        class: AppBundle\Repository\DefaultRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Seance

    app.repository.seance_price:
        class: AppBundle\Repository\DefaultRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\SeancePrice

    app.repository.user_order:
        class: AppBundle\Repository\DefaultRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\UserOrder

    #Services
    app.service.sms:
        class: AppBundle\Service\SmsService
        arguments:
            - "%twilio%"
            - "%project_name%"

    # Services entity
    app.service.entity.user:
        class: AppBundle\Service\Entity\UserService
        arguments:
            - "@validator"
            - "%security.role_hierarchy.roles%"
        calls:
            - [setRepository, ['@app.repository.user']]
            - [setSmsService, ['@app.service.sms']]
            - [setLocalityRepository, ['@app.repository.locality']]